### ISSUE TITLE
split run test script in subcomponents

### ISSUE THREAD

**Issue by christianpaquin** [open-quantum-safe/testing#1]
As discussed on the dev call, we could add a travis test in the openssl projects to download and run the integration/oqs_openssl/run[2] script. Since the openssl project already has it's own code, it would be good split the script in subcomponents, for example: build-liboqs-master, build-liboqs-nist, build-openssl-1.0.2, build-openssl-1.1.1, run-openssl-1.0.2-tests, and run-openssl-1.1.1-tests. This way the openssl travis test could skip the build-openssl-* subscripts, and reuse the code to build liboqs and run the openssl tests.

**Comment by dstebila** [comment]
Do we still want to do this?  @truth-quark any insights based on recent changes you made to enable Travis?

**Comment by truth-quark** [comment]
> Do we still want to do this? @truth-quark any insights based on recent changes you made to enable Travis?

Firstly, is the gist to replicate something like the function oriented layout of https://github.com/open-quantum-safe/testing/blob/master/integration/oqs_openssh/run.sh?

**Comment by dstebila** [comment]
Not just to replicate the function oriented layout, but also allow the user to run a subset of the tests.  When I was debugging stuff, sometimes the third or fourth test would fail, so I'd have to either comment stuff out or run the whole suite from the beginning.

But this is pretty low priority right now.

**Comment by dstebila** [comment]
Fixed by #28.
