### ISSUE TITLE
Possible build step duplication?

### ISSUE THREAD

**Issue by truth-quark** [open-quantum-safe/testing#15]
Line 177 repeats the build step at line 164:

https://github.com/open-quantum-safe/testing/blob/cee55b93cd8aa616ed1def3f7e3365e04973456e/integration/oqs_openssh/run.sh#L164
https://github.com/open-quantum-safe/testing/blob/cee55b93cd8aa616ed1def3f7e3365e04973456e/integration/oqs_openssh/run.sh#L177

With cutting CI runtime in mind, is there anything preventing us from keeping the SSL build parts for the liboqs-nist integration test?

**Comment by dstebila** [comment]
Good idea, but the `rm -rf install` will wipe out the install of OpenSSL, so you'd need to re-install it again.  Could do this with a `make install` inside OpenSSL dir, but that's slow, so possibly do a backup of the install dir after the first build\_openssl, then copy it back in in place of the second build\_openssl.

**Comment by dstebila** [comment]
Is this still relevant, @truth-quark?

**Comment by truth-quark** [comment]
> Is this still relevant, @truth-quark?

Yes, it should help cut down on build/test run time from duplicate work (travis integration builds take 30-40 mins overall). I didn't get a chance to look at it as travis/vagrant kept breaking. It's also related to https://github.com/open-quantum-safe/testing/issues/16 (now closed, some options there weren't looked at with the travis builds breaking until this week).

**Comment by dstebila** [comment]
Fixed by #28.
