### ISSUE TITLE
Optimise build speed on travis

### ISSUE THREAD

**Issue by truth-quark** [open-quantum-safe/testing#16]
Adding an issue here for documentation/reference purposes:

Options to try:
* Caching dependencies
* Caching compiler outputs
* Reduce/share builds of components?
* Reduce number of containers in matrix (e.g. don't test all combos of Ubu 14, 16 vs 3 GCC versions)
* Cache brew step for Mac test containers?
* ...

Links
* https://docs.travis-ci.com/user/speeding-up-the-build/
* https://docs.travis-ci.com/user/installing-dependencies/
* https://docs.travis-ci.com/user/caching/

**Comment by truth-quark** [comment]
Travis docs suggest **ccache**: https://ccache.samba.org/
From the limitations section: _Only knows how to cache the compilation of a single C/C++/Objective-C/Objective-C++ file. Other types of compilations (multi-file compilation, linking, etc) will silently fall back to running the real compiler._

* Limitation implies changing liboqs makefiles to make use of ccache
* TODO: result of adding ccache to travis config to "see what happens".

**Comment by truth-quark** [comment]
Can the build matrix be split to execute the two run.sh tests independently?

**Comment by dstebila** [comment]
Fixed by #20.
