### ISSUE TITLE
Automate VM setup & test execution

### ISSUE THREAD

**Issue by truth-quark** [open-quantum-safe/testing#21]
Add a run all script to:
* perform all documented pk install steps
* execute the run.sh scripts for openssl and openssh

Rationale: make it faster and less error prone to run the integration tests on target systems.

**Comment by truth-quark** [comment]
See https://github.com/open-quantum-safe/testing/tree/run-all-script

**Comment by truth-quark** [comment]
The PR is here: https://github.com/open-quantum-safe/testing/pull/22

**Comment by dstebila** [comment]
Fixed by #22.
